f0 = 256;
dt = 1/16;
tk = (0:1024)*dt;
st = sin(2*pi*tk)+cos(pi*tk);   % 1) the ordinary signal
max_of_st = max(st);
encoded = alaw(st);               % 2) encoded by A-law
modulated = bpsk(encoded, f0);    % 3) modulated by BPSK
demodulated = debpsk(modulated, f0);  % 4) demodulated
decoded = dealaw(demodulated, max_of_st);  % 5) decoded